version: '3.9'

services:
  cin_validator:
    image: faroukdaboussi0/id_card_service:latest
    container_name: id_card_service
    volumes:
      - ./api_keys.env:/app/api_keys.env        
      - ./logs/:/app/app/logs/                  
    ports:
      - "8000:8000"
    restart: unless-stopped
